# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11CkPM8aqJV_X3r-XwBxBurPtxuaJhD1W
"""

import cv2
import os
from google.colab.patches import cv2_imshow

rasm_teraflyu = "/content/5467823479450632042.jpg"
rasm_bolnol = "/content/5467823479450632043.jpg"
rasm_kupen = "/content/5467823479450632045.jpg"
rasm_loratal = "/content/5467823479450632048.jpg"
rasm_parasetamol = "/content/5467823479450632050.jpg"
rasm_kreon = "/content/5467823479450632051.jpg"
rasm_ass = "/content/5467823479450632054.jpg"

# Funksiya
def kasallik_tashxisi(belgi):
    if belgi == 'grip':
        rasm_joylash = rasm_teraflyu
        return "Teraflyu iching", rasm_joylash
    elif belgi == 'bosh ogrigi':
        rasm_joylash = rasm_bolnol
        return "Bolnol iching", rasm_joylash
    elif belgi == 'tish ogrigi':
        rasm_joylash = rasm_kupen
        return "Kupen iching", rasm_joylash
    elif belgi == 'allergiya':
        rasm_joylash = rasm_loratal
        return "Loratal iching", rasm_joylash
    elif belgi == 'istima':
        rasm_joylash = rasm_parasetamol
        return "Parasetamol iching", rasm_joylash
    elif belgi == 'qorin ogrigi':
        rasm_joylash = rasm_kreon
        return "Kreon iching", rasm_joylash
    elif belgi == 'yotal':
        rasm_joylash = rasm_ass
        return "Ass iching", rasm_joylash
    else:
        return "Aniqlanmagan belgi", None

# Foydalanuvchidan belgi kiritish
belgi = input("Kasallik belgisini kiriting: ").strip().lower()

# Natijani chiqarish
natija, rasm_fayl = kasallik_tashxisi(belgi)
print(natija)

# Agar rasm mavjud bo‘lsa, chiqarish
if rasm_fayl and os.path.exists(rasm_fayl):
    rasm = cv2.imread(rasm_fayl)
    if rasm is not None:
        cv2_imshow(rasm)
    else:
        print("Rasmni ochib bo'lmadi.")
elif rasm_fayl:
    print(f"Rasm fayli topilmadi: {rasm_fayl}")

